//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCI.HashAssistant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCI.HashAssistant.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string DialogTitleInformation {
            get {
                return ResourceManager.GetString("DialogTitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Result: {0}
        ///
        ///Expected Hash Value: {1}
        ///
        ///Actual Hash Value: {2}.
        /// </summary>
        internal static string Msg_CheckHashResult {
            get {
                return ResourceManager.GetString("Msg_CheckHashResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Assistant Tool 
        ///- Calculate the hash value with SHA512 algorithm.
        ///- Check if the hash value is as expected for a specified file.
        ///
        ///Usage: HashAssistant.exe [File full path] [Hash file name]
        ///
        ///[File full path]: Required. The full file path of the file to calculate the hash value.
        ///[Hash file name]: Optional. The file name which store the calculated hash value. The file will be saved in the same directory with the file that checks hash value if the argument only includes hash file name. The default h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Msg_CmdLinePrompt {
            get {
                return ResourceManager.GetString("Msg_CmdLinePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute hash.
        ///
        ///Detailed Error: {0}.
        /// </summary>
        internal static string Msg_ComputeHashError {
            get {
                return ResourceManager.GetString("Msg_ComputeHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the expected hash value..
        /// </summary>
        internal static string Msg_InputHashPrompt {
            get {
                return ResourceManager.GetString("Msg_InputHashPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load hash file.
        ///
        ///Detailed Error: {0}.
        /// </summary>
        internal static string Msg_ReadHashFileError {
            get {
                return ResourceManager.GetString("Msg_ReadHashFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file to check..
        /// </summary>
        internal static string Msg_SelectFilePrompt {
            get {
                return ResourceManager.GetString("Msg_SelectFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All File|*.*.
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pass {
            get {
                object obj = ResourceManager.GetObject("pass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
